//! Full-suite regression pass — Phase 7 Task 126 (`mo-uj3ke`), expanded by
//! Task 148 (`mo-6oj`).
//!
//! Runs **all 40 characterization fixtures** (30 onroad + 10 NONROAD; the 3
//! `scale-*` fixtures that require additional input databases and the 3
//! `error-*` fixtures that are expected to fail are both excluded from the
//! smoke-test suite) through the complete Rust port and verifies:
//!
//! # Scale fixtures (County / Project / Rates)
//!
//! The three `scale-*` fixtures (`scale-county`, `scale-project`,
//! `scale-rates`) require a County/Project-scale input directory (CDB/PDB
//! Parquet) that is not bundled in the repo.  Set
//! [`SCALE_INPUTS_DIR_ENV`] to a directory containing the per-fixture
//! sub-directories (e.g. `<dir>/scale-county/*.parquet`) to activate the
//! scale-fixture gate.  Without the env var these tests are **dormant** —
//! they print a notice and pass.
//!
//! When `SCALE_INPUTS_DIR` is set **and** canonical MOVES snapshots are
//! available under [`SNAPSHOTS_DIR_ENV`], the canonical-diff gate activates
//! for the scale fixtures too, using the same `characterization/tolerance.toml`
//! budget as the default-scale fixtures.
//!
//! # Canonical MOVES availability
//!
//! The canonical MOVES SIF (`characterization/apptainer/moves-fixture.sif`)
//! was **not present** on the implementation machine at Task 144 author time.
//! Reference snapshots for `scale-county`, `scale-project`, and `scale-rates`
//! therefore need to be generated by a separate canonical-MOVES run on an
//! Apptainer-capable HPC node (see `characterization/run-all-fixtures.sh
//! --include scale-county --include scale-project --include scale-rates`).
//! Until those snapshots exist, the canonical-diff gate for the scale
//! fixtures remains dormant even when `SCALE_INPUTS_DIR` is set.
//!
//! 1. **No fixture panics or errors** — every `moves run` invocation returns
//!    `Ok(outcome)` and produces a `MOVESRun.parquet` metadata file.
//! 2. **Module plan is non-empty** — every fixture exercises at least one
//!    calculator-graph module, confirming the RunSpec parses and the DAG
//!    filters correctly for both the onroad and NONROAD model paths.
//! 3. **Canonical-snapshot diff (active)** — [`canonical_snapshot_diff`] runs
//!    each fixture with `--snapshot` (so the calculators execute against the
//!    captured execution DB and the engine writes the real `MOVESOutput/`
//!    tree), then compares the port's per-pollutant `emissionQuant` totals
//!    against the canonical `MOVESOutput` table. It hard-asserts on the
//!    fixtures whose data plane matches canonical within a documented
//!    precision-only tolerance and prints — without asserting — the divergence
//!    for fixtures with a known, reported data-plane bug. See the catalogue in
//!    `docs/known-divergences.md`.
//!
//! # Why per-pollutant sums, not a cell diff
//!
//! Even where the port reproduces canonical to `f64` precision, the two
//! `MOVESOutput` tables disagree on metadata/labeling columns that do not
//! affect emitted mass (`iterationID`, `roadTypeID`, the `SCC` road-type
//! subfield) and on which uncertainty columns are present. A cell-level
//! [`moves_snapshot::diff_snapshots`] therefore fails on every fixture; the
//! per-pollutant `emissionQuant` total is the quantity that must agree and is
//! the same metric `characterization/audit/regression_gate.sh` uses.
//!
//! # Running the gate explicitly
//!
//! ```sh
//! cargo test --test full_suite_regression canonical_snapshot_diff -- --nocapture
//! ```
//!
//! Point it at a different snapshot tree with
//! `REGRESSION_SNAPSHOTS_DIR=<path>`.

use std::path::{Path, PathBuf};

use moves_cli::{run_simulation, RunOptions};
use moves_snapshot::{
    compare_pollutant_sums, diff_snapshots, pollutant_sums_from_output_dir,
    pollutant_sums_from_snapshot, DiffOptions, Snapshot, ToleranceConfig,
};
use tempfile::tempdir;

/// Environment variable naming the directory of Phase 0 canonical-MOVES
/// snapshots. Unset → the in-repo `characterization/snapshots/` tree, which is
/// populated (all 34 non-scale fixtures), so the diff gate is active.
pub const SNAPSHOTS_DIR_ENV: &str = "REGRESSION_SNAPSHOTS_DIR";

/// Environment variable naming the root directory that holds per-fixture
/// County/Project-scale (CDB/PDB) Parquet inputs.
///
/// The layout expected under this root is:
/// ```text
/// <dir>/
///   scale-county/   ← *.parquet produced by `moves import-cdb`
///   scale-project/  ← *.parquet produced by the PDB importer
///   scale-rates/    ← *.parquet (Rates mode uses County-scale CDB inputs)
/// ```
/// When this variable is unset (or empty) the scale-fixture tests are dormant.
pub const SCALE_INPUTS_DIR_ENV: &str = "SCALE_INPUTS_DIR";

// ── helpers ──────────────────────────────────────────────────────────────────

fn workspace_root() -> PathBuf {
    PathBuf::from(env!("CARGO_MANIFEST_DIR"))
        .parent()
        .and_then(Path::parent)
        .expect("workspace root above crates/moves-cli/")
        .to_path_buf()
}

fn fixtures_dir() -> PathBuf {
    workspace_root().join("characterization/fixtures")
}

/// The canonical snapshot root, overridable by [`SNAPSHOTS_DIR_ENV`].
fn snapshots_root() -> PathBuf {
    std::env::var_os(SNAPSHOTS_DIR_ENV)
        .map(PathBuf::from)
        .filter(|p| !p.as_os_str().is_empty())
        .unwrap_or_else(|| workspace_root().join("characterization").join("snapshots"))
}

/// The scale-inputs root directory, or `None` when [`SCALE_INPUTS_DIR_ENV`] is
/// not set or does not point to a directory.
fn scale_inputs_root() -> Option<PathBuf> {
    std::env::var_os(SCALE_INPUTS_DIR_ENV)
        .map(PathBuf::from)
        .filter(|p| !p.as_os_str().is_empty() && p.is_dir())
}

/// Path to the cell-level tolerance config (used only by the dormant scale-diff gate).
fn tolerance_config_path() -> PathBuf {
    workspace_root().join("characterization/tolerance.toml")
}

/// `DiffOptions` for the dormant scale-fixture cell-level diff gate.
fn tolerance_opts() -> DiffOptions {
    let path = tolerance_config_path();
    if path.is_file() {
        ToleranceConfig::from_file(&path)
            .map(Into::into)
            .unwrap_or_default()
    } else {
        DiffOptions::default()
    }
}

/// All non-`scale-*`, non-`error-*` fixture XML paths in sorted order.
///
/// 46 total fixtures; 3 `scale-*` excluded (require additional input
/// databases), 3 `error-*` excluded (expected parse errors — tested by
/// [`error_fixtures_return_expected_errors`]). Result: 30 onroad (including
/// mixed-onroad-nonroad) + 10 NONROAD = 40 fixtures.
fn all_fixtures() -> Vec<PathBuf> {
    let dir = fixtures_dir();
    let mut paths: Vec<PathBuf> = std::fs::read_dir(&dir)
        .unwrap_or_else(|e| panic!("read fixtures dir {}: {e}", dir.display()))
        .filter_map(|e| e.ok())
        .map(|e| e.path())
        .filter(|p| {
            let name = p.file_name().and_then(|n| n.to_str()).unwrap_or_default();
            p.extension().and_then(|x| x.to_str()) == Some("xml")
                && !name.starts_with("scale-")
                && !name.starts_with("error-")
        })
        .collect();
    paths.sort();
    paths
}

fn fixture_name(path: &Path) -> &str {
    path.file_stem().and_then(|n| n.to_str()).unwrap_or("?")
}

fn canonical_present(snapshots_root: &Path, name: &str) -> bool {
    snapshots_root.join(name).join("manifest.json").is_file()
}

// ── fixture catalogue ─────────────────────────────────────────────────────────

/// The fixture catalogue must contain exactly 40 non-scale non-error fixtures.
///
/// 46 total in `characterization/fixtures/`:
/// - 30 onroad/mixed (non-`nr-`, non-`scale-`, non-`error-`):
///   23 original default-scale + `mixed-onroad-nonroad` + 6 added by Task 148
///   (`expand-counties-large`, `expand-multifuel`, `expand-fullyear`,
///   `expand-multiyear`, `expand-roadtypes`, `rates-minimal`)
/// - 10 NONROAD (`nr-*.xml`)
/// - 3 `scale-*.xml` (excluded — require additional input databases)
/// - 3 `error-*.xml` (excluded — test expected parse failures separately)
#[test]
fn fixture_catalogue_size() {
    let fixtures = all_fixtures();
    assert_eq!(
        fixtures.len(),
        40,
        "expected 40 non-scale non-error fixtures (30 onroad/mixed + 10 NONROAD), \
         found {}. Update this test if the catalogue changes.",
        fixtures.len()
    );

    let onroad_count = fixtures
        .iter()
        .filter(|p| !fixture_name(p).starts_with("nr-"))
        .count();
    let nonroad_count = fixtures
        .iter()
        .filter(|p| fixture_name(p).starts_with("nr-"))
        .count();

    assert_eq!(
        onroad_count, 30,
        "expected 30 onroad/mixed fixtures, found {onroad_count}"
    );
    assert_eq!(
        nonroad_count, 10,
        "expected 10 NONROAD fixtures (nr-*), found {nonroad_count}"
    );
}

// ── always-active smoke tests ─────────────────────────────────────────────────

/// Every fixture must complete without error and produce a non-empty module plan.
///
/// Prints a regression table matching `docs/known-divergences.md`.
#[test]
fn all_fixtures_run_without_error() {
    let fixtures = all_fixtures();
    assert!(!fixtures.is_empty(), "no fixtures found");

    println!(
        "\n{:<42} {:>8} {:>8} {:>8}",
        "fixture", "planned", "executed", "unimpl"
    );
    println!("{}", "-".repeat(72));

    let mut failures: Vec<String> = Vec::new();

    for fixture in &fixtures {
        let name = fixture_name(fixture);
        let out = tempdir().expect("tempdir");
        let result = run_simulation(&RunOptions {
            runspec: fixture.clone(),
            output: out.path().to_path_buf(),
            max_parallel_chunks: 1,
            calculator_dag: None,
            run_date_time: Some("2026-05-21T00:00:00".to_string()),
            snapshot: None,
            scale_input: None,
        });

        match result {
            Err(e) => {
                failures.push(format!("{name}: {e}"));
                println!("{name:<42} ERROR");
            }
            Ok(outcome) => {
                if !outcome.run_record_path.is_file() {
                    failures.push(format!("{name}: MOVESRun.parquet missing"));
                }
                if outcome.modules_planned.is_empty() {
                    failures.push(format!("{name}: no modules planned"));
                }
                println!(
                    "{name:<42} {:>8} {:>8} {:>8}",
                    outcome.modules_planned.len(),
                    outcome.modules_executed.len(),
                    outcome.modules_unimplemented.len(),
                );
            }
        }
    }

    println!("{}", "-".repeat(72));
    println!("{} fixtures", fixtures.len());

    assert!(
        failures.is_empty(),
        "full-suite regression failures:\n  {}",
        failures.join("\n  ")
    );
}

/// NONROAD fixtures must plan at least one module independently of the
/// onroad calculator-graph path.
#[test]
fn nonroad_fixtures_plan_modules() {
    let fixtures: Vec<PathBuf> = all_fixtures()
        .into_iter()
        .filter(|p| fixture_name(p).starts_with("nr-"))
        .collect();
    assert_eq!(fixtures.len(), 10);

    for fixture in &fixtures {
        let name = fixture_name(fixture);
        let out = tempdir().expect("tempdir");
        let outcome = run_simulation(&RunOptions {
            runspec: fixture.clone(),
            output: out.path().to_path_buf(),
            max_parallel_chunks: 1,
            calculator_dag: None,
            run_date_time: Some("2026-05-21T00:00:00".to_string()),
            snapshot: None,
            scale_input: None,
        })
        .unwrap_or_else(|e| panic!("{name}: {e}"));
        assert!(
            !outcome.modules_planned.is_empty(),
            "{name}: no modules planned"
        );
    }
}

// ── error-fixture gate ────────────────────────────────────────────────────────

/// Every `error-*` fixture must fail to parse and produce a clear, actionable
/// error message (no panics, no cryptic internal errors).
///
/// Each `error-*.xml` in `characterization/fixtures/` is a deliberately
/// invalid RunSpec. The test asserts:
/// 1. `run_simulation` returns `Err(...)` (not `Ok`).
/// 2. The error message contains a human-readable description of the problem
///    — not a Rust panic backtrace or an opaque internal code.
///
/// Added by Task 148 (`mo-6oj`) to characterize the error-handling paths.
#[test]
fn error_fixtures_return_expected_errors() {
    let dir = fixtures_dir();
    let mut error_fixtures: Vec<PathBuf> = std::fs::read_dir(&dir)
        .unwrap_or_else(|e| panic!("read fixtures dir {}: {e}", dir.display()))
        .filter_map(|e| e.ok())
        .map(|e| e.path())
        .filter(|p| {
            let name = p.file_name().and_then(|n| n.to_str()).unwrap_or_default();
            p.extension().and_then(|x| x.to_str()) == Some("xml") && name.starts_with("error-")
        })
        .collect();
    error_fixtures.sort();

    assert!(
        !error_fixtures.is_empty(),
        "no error-* fixtures found under {}",
        dir.display()
    );

    let expected: &[(&str, &str)] = &[
        ("error-bad-geotype", "invalid enum value for geographicselection.type"),
        ("error-bad-model", "invalid enum value for models.model.value"),
        ("error-bad-modelscale", "invalid enum value for modelscale.value"),
    ];

    let mut failures: Vec<String> = Vec::new();

    for fixture in &error_fixtures {
        let name = fixture_name(fixture);
        let out = tempdir().expect("tempdir");
        let result = run_simulation(&RunOptions {
            runspec: fixture.clone(),
            output: out.path().to_path_buf(),
            max_parallel_chunks: 1,
            calculator_dag: None,
            run_date_time: Some("2026-05-21T00:00:00".to_string()),
            snapshot: None,
            scale_input: None,
        });

        match result {
            Ok(_) => {
                failures.push(format!(
                    "{name}: expected Err but got Ok — fixture should trigger a parse error"
                ));
            }
            Err(e) => {
                // Collect the full error chain so we see the root cause, not
                // just the outermost `anyhow` context frame.
                let msg: String = e
                    .chain()
                    .map(|c| c.to_string())
                    .collect::<Vec<_>>()
                    .join(": ");
                // Require a non-panic, human-readable message.
                if msg.contains("panicked at") || msg.contains("thread 'main' panicked") {
                    failures.push(format!("{name}: got a panic instead of a clean error: {msg}"));
                    continue;
                }
                // Check the expected error substring for known fixtures.
                if let Some((_, expected_substr)) =
                    expected.iter().find(|(n, _)| *n == name)
                {
                    if !msg.contains(expected_substr) {
                        failures.push(format!(
                            "{name}: error message does not contain \
                             expected substring {expected_substr:?}; got: {msg}"
                        ));
                    } else {
                        println!("{name}: ok — {msg}");
                    }
                } else {
                    // Unknown error fixture — just require it returns an error.
                    println!("{name}: ok (unknown fixture, got error) — {msg}");
                }
            }
        }
    }

    assert!(
        failures.is_empty(),
        "error-fixture gate failures:\n  {}",
        failures.join("\n  ")
    );
}

// ── canonical-diff gate ───────────────────────────────────────────────────────

/// Per-pollutant relative-difference tolerance for **onroad** fixtures whose
/// data plane is wired and matches canonical. The float-summation order differs
/// between canonical MOVES (MariaDB) and the Rust port (`f64` Polars), producing
/// sub-`1e-4` relative drift on the `emissionQuant` totals. See
/// `docs/known-divergences.md` §4.2.
const ONROAD_REL_TOL: f64 = 1e-3;

/// Per-pollutant relative-difference tolerance for **NONROAD** fixtures. NONROAD
/// arithmetic is Fortran single-precision (`real*4`) in canonical MOVES; the
/// Rust port uses `f64` throughout, so the totals differ by a documented
/// half-percent-scale amount even when the physics is reproduced exactly. See
/// `docs/known-divergences.md` §4.2.
const NONROAD_REL_TOL: f64 = 1e-2;

/// Floor on the relative-difference denominator so a pollutant that is exactly
/// zero in canonical does not yield an infinite relative difference.
const REL_DIFF_FLOOR: f64 = 1e-30;

/// Fixtures whose `MOVESOutput` matches canonical within tolerance and which the
/// gate therefore **hard-asserts**. A regression that pushes any of these out of
/// tolerance fails the test.
///
/// `vacuous` marks fixtures whose canonical snapshot has no `MOVESOutput` rows
/// (the selected process is not materialised in the capture); the port likewise
/// emits nothing, so there is no divergence to measure. They are pinned here so
/// that if either side starts producing rows the asymmetry is caught.
fn asserted_fixtures() -> &'static [(&'static str, f64, bool)] {
    &[
        // (fixture, per-pollutant relative tolerance, vacuous)
        ("process-evap-fvv", ONROAD_REL_TOL, false), // ~8.2e-5
        ("process-evap-leaks", ONROAD_REL_TOL, false), // ~1.6e-7
        ("process-evap-permeation", ONROAD_REL_TOL, false), // ~2.1e-7
        ("nr-commercial-nation", NONROAD_REL_TOL, false), // ~3.5e-3 (real*4)
        // process-apu was asserted-vacuous (canon 0 / port 0) only because the
        // month off-by-one blocked all BaseRate output. With that fixed the
        // BaseRate path now emits the process-91 / opMode-201,203 (APU /
        // shorepower) energy rates, which canonical drops from baseRateOutput
        // (its baserateoutput is 0 even though baserate_91_2020 has 358 rows
        // and a baserateunits row exists). Reproducing that requires the
        // runspec-derived BRC activity gating the port has not yet wired —
        // see QUARANTINED_FIXTURES and docs/known-divergences.md §4.4.
        ("process-crankcase-extidle", ONROAD_REL_TOL, true),
        ("process-crankcase-start", ONROAD_REL_TOL, true),
        ("process-extended-idle", ONROAD_REL_TOL, true),
    ]
}

/// Fixtures with a **known, reported data-plane bug** whose `MOVESOutput`
/// diverges from canonical far beyond any precision budget. They are run and
/// their divergence is printed for visibility, but the gate does **not** assert
/// on them — masking the bug with a widened tolerance would be worse than no
/// gate (a real-bug divergence must be fixed in the data plane, never hidden).
/// Each entry is catalogued in `docs/known-divergences.md` §4.4. As a fixture's
/// data plane is fixed it should graduate from this list into
/// [`asserted_fixtures`].
const QUARANTINED_FIXTURES: &[&str] = &[
    // OVER-emit class — ROW SHAPE now matches canonical (process / road type /
    // pollutant / row count), but the emitted MASS does not. Two causes were
    // separated: (1) the port emitted off-network start-exhaust rows (process 2,
    // roadTypeID 1) the RunSpec never selected — FIXED by mirroring the MOVES
    // worker's `runSpecRoadType` join inside `BaseRateCalculator::execute`; and
    // (2) the surviving rows carry the raw BaseRate rate, not `rate × activity`
    // — the per-model-year inventory activity weighting (`universalActivity`,
    // built by canonical from SHO × source-bin × age and never persisted) is not
    // yet wired, so `emissionQuant` is off by the missing fleet-population
    // factor (max_rel_diff ≈ 0.83 for expand-criteria). Still quarantined on
    // mass. See docs/known-divergences.md §4.4 reported bug 1.
    "expand-counties",
    "expand-criteria",
    "expand-day",
    "expand-fueltype-diesel",
    "expand-month",
    "expand-sourcetype",
    "sample-runspec",
    // process-apu: BaseRate emits the process-91 / op-mode-201,203 (APU /
    // shorepower) energy rates canonical activity-gates to 0 in baseRateOutput;
    // same missing-activity-weighting gap. mixed-onroad-nonroad: canonical
    // MOVESOutput is empty (0 rows) while the port's NONROAD half emits ~8,632
    // legitimate rows (separate/known). See docs/known-divergences.md §4.4.
    "process-apu",
    "mixed-onroad-nonroad",
    // UNDER-emit class — calculator-chain coverage gaps (a DIFFERENT bug from
    // the over-emit above): downstream speciation / chained calculators fire but
    // produce no rows for several pollutants/processes, so the port emits FEWER
    // rows than canonical. process-pm-exhaust emits only PM components 112/118
    // (the two BasicRunningPM produces) and is missing 100/110/111/115/119;
    // process-airtoxics / process-nox-speciation / chain-* emit one base
    // process's worth where canonical has the full speciated set; brakewear /
    // tirewear / crankcase-running under-emit a whole slice (and also carry the
    // activity-weighting mass gap). process-refueling emits the WRONG content —
    // BaseRate energy (process 1 / pollutant 91) instead of refueling THC
    // (processes 18/19 / pollutant 1), whose calculator is not wired. See
    // docs/known-divergences.md §4.4 reported bug 3.
    "chain-nonhaptog",
    "chain-tog-speciation",
    "process-airtoxics",
    "process-brakewear",
    "process-crankcase-running",
    "process-nox-speciation",
    "process-pm-exhaust",
    "process-refueling",
    "process-tirewear",
    // NONROAD fixtures that emit nothing (port row count 0 vs a populated
    // canonical) or a wrong row count — population/sector-coverage gaps.
    "nr-agriculture-state",
    "nr-airport-support-county",
    "nr-construction-state",
    "nr-industrial-county",
    "nr-lawn-garden-county",
    "nr-logging-county",
    "nr-pleasure-craft-state",
    "nr-railroad-support-nation",
    "nr-recreational-county",
];

fn is_quarantined(name: &str) -> bool {
    QUARANTINED_FIXTURES.contains(&name)
}

/// Compare each fixture's **real `MOVESOutput`** against its canonical-MOVES
/// snapshot, per-pollutant, with `--snapshot` active.
///
/// **Dormant** unless [`SNAPSHOTS_DIR_ENV`] points at a populated snapshot tree
/// (or the in-repo `characterization/snapshots/` tree is populated, which it is)
/// AND the fixture's snapshot sub-directory contains a `manifest.json`.
///
/// For every covered fixture the test:
/// 1. Runs the port with `snapshot: Some(<canonical-dir>)`, so the calculators
///    execute against the captured execution database and the engine writes the
///    real `MOVESOutput/` partitioned Parquet tree (not just `MOVESRun.parquet`).
/// 2. Sums `emissionQuant` per `pollutantID` from both the canonical
///    `MOVESOutput` table and the port's `MOVESOutput/` tree.
/// 3. Compares the per-pollutant totals.
///
/// Why per-pollutant sums rather than a cell-level [`diff_snapshots`]? Even where
/// the port reproduces canonical to `f64` precision, the two `MOVESOutput` tables
/// disagree on metadata/labeling columns that do not affect emitted mass
/// (`iterationID` NULL vs 1, `roadTypeID` 0 vs the link road type, and the `SCC`
/// road-type subfield), and canonical carries `emissionQuantMean`/`Sigma` where
/// the port carries `emissionRate`/`runHash`. A cell diff fails on those for
/// every fixture; the per-pollutant `emissionQuant` total is the quantity that
/// must agree and cleanly isolates real divergences in emitted mass. This is the
/// same metric as `characterization/audit/regression_gate.sh`.
///
/// The gate hard-asserts on [`asserted_fixtures`] and prints — without asserting
/// — the divergence for [`QUARANTINED_FIXTURES`] (known, reported data-plane
/// bugs; see `docs/known-divergences.md` §4.4).
#[test]
fn canonical_snapshot_diff() {
    let root = snapshots_root();
    let fixtures = all_fixtures();

    let covered: Vec<&Path> = fixtures
        .iter()
        .map(|p| p.as_path())
        .filter(|p| canonical_present(&root, fixture_name(p)))
        .collect();

    if covered.is_empty() {
        println!(
            "\n[canonical_snapshot_diff] DORMANT\n\
             No canonical snapshots under '{}'.\n\
             See docs/known-divergences.md for how to enable this gate.",
            root.display()
        );
        return;
    }

    println!(
        "\n[canonical_snapshot_diff] {} fixture(s) against {}",
        covered.len(),
        root.display()
    );
    println!(
        "{:<28} {:>10} {:>10} {:>14} {:>10}",
        "fixture", "canon_rows", "port_rows", "max_rel_diff", "verdict"
    );
    println!("{}", "-".repeat(78));

    let mut failures: Vec<String> = Vec::new();
    let mut passed = 0usize;
    let mut quarantined = 0usize;

    for fixture_path in covered {
        let name = fixture_name(fixture_path);
        let out = tempdir().expect("tempdir");

        let outcome = run_simulation(&RunOptions {
            runspec: fixture_path.to_path_buf(),
            output: out.path().to_path_buf(),
            max_parallel_chunks: 1,
            calculator_dag: None,
            run_date_time: Some("2026-05-21T00:00:00".to_string()),
            // Activate the data plane: calculators execute against the captured
            // execution DB and the engine writes the real MOVESOutput tree.
            snapshot: Some(root.join(name)),
            scale_input: None,
        })
        .unwrap_or_else(|e| panic!("{name}: run error — {e}"));

        let canonical = match Snapshot::load(&root.join(name)) {
            Ok(s) => pollutant_sums_from_snapshot(&s),
            Err(e) => {
                println!("{name:<28} canonical load error: {e}");
                failures.push(format!("{name}: canonical load error: {e}"));
                continue;
            }
        };
        let port = pollutant_sums_from_output_dir(outcome.output_root.as_path())
            .unwrap_or_else(|e| panic!("{name}: reading port MOVESOutput — {e}"));

        let cmp = compare_pollutant_sums(&canonical, &port, REL_DIFF_FLOOR);

        let asserted = asserted_fixtures().iter().find(|(n, _, _)| *n == name);
        let verdict = if let Some((_, tol, vacuous)) = asserted {
            // Hard-asserted fixture.
            let row_mismatch = canonical.row_count != port.row_count;
            let within = cmp.within(*tol);
            if *vacuous {
                if canonical.row_count == 0 && port.row_count == 0 {
                    passed += 1;
                    "PASS(empty)"
                } else {
                    failures.push(format!(
                        "{name}: expected vacuous (0 rows both) but canon={} port={}",
                        canonical.row_count, port.row_count
                    ));
                    "FAIL"
                }
            } else if within && !row_mismatch {
                passed += 1;
                "PASS"
            } else {
                failures.push(format!(
                    "{name}: max_rel_diff={:.3e} (tol {:.0e}), canon_rows={} port_rows={}",
                    cmp.max_rel_diff, tol, canonical.row_count, port.row_count
                ));
                "FAIL"
            }
        } else if is_quarantined(name) {
            quarantined += 1;
            // HARD-FAIL (operator decision): known data-plane bugs turn CI red —
            // it is OK for CI to be red while results are wrong. Each fixture
            // graduates out of QUARANTINED_FIXTURES into asserted_fixtures once
            // its data plane is fixed. See docs/known-divergences.md §4.4.
            failures.push(format!(
                "{name}: KNOWN DATA-PLANE BUG — max_rel_diff={:.3e}, canon_rows={} \
                 port_rows={} — see docs/known-divergences.md §4.4",
                cmp.max_rel_diff, canonical.row_count, port.row_count
            ));
            "BUG(FAIL)"
        } else {
            // A covered fixture that is neither asserted nor quarantined is an
            // unclassified divergence: fail loudly so it gets triaged rather
            // than silently ignored.
            failures.push(format!(
                "{name}: UNCLASSIFIED max_rel_diff={:.3e}, canon_rows={} port_rows={} — \
                 add to asserted_fixtures (with a documented precision-only tolerance) \
                 or QUARANTINED_FIXTURES (with a docs/known-divergences.md bug entry)",
                cmp.max_rel_diff, canonical.row_count, port.row_count
            ));
            "UNCLASS"
        };

        println!(
            "{name:<28} {:>10} {:>10} {:>14.3e} {:>10}",
            canonical.row_count, port.row_count, cmp.max_rel_diff, verdict
        );
    }

    println!("{}", "-".repeat(78));
    println!(
        "{passed} asserted-pass, {quarantined} known-bug hard-fail, \
         {} total failure(s)",
        failures.len()
    );

    assert!(
        failures.is_empty(),
        "canonical-snapshot gate failures (these are regressions in the \
         asserted set or unclassified divergences — fix the data plane, do not \
         widen tolerances to mask a real bug):\n  {}",
        failures.join("\n  ")
    );
}

// ── scale-fixture gate ────────────────────────────────────────────────────────

/// Run the three County/Project/Rates-scale fixtures and check they complete
/// without error.
///
/// **Dormant** unless [`SCALE_INPUTS_DIR_ENV`] points at a populated inputs
/// root (see module docs).  When active, each fixture:
///
/// 1. Runs `moves run` with `scale_input` pointing at its per-fixture
///    sub-directory under the scale-inputs root.
/// 2. Asserts no error, a non-empty module plan, and a `MOVESRun.parquet`
///    metadata file.
///
/// The canonical-diff gate (comparing against a Phase 0 canonical-MOVES
/// snapshot) requires the reference snapshots to be generated separately —
/// see [`SNAPSHOTS_DIR_ENV`] and the module-level docs for details.
#[test]
fn scale_fixtures_run_without_error() {
    let scale_root = match scale_inputs_root() {
        Some(r) => r,
        None => {
            println!(
                "\n[scale_fixtures_run_without_error] DORMANT\n\
                 Set {SCALE_INPUTS_DIR_ENV}=<dir> to a root with scale-county/, \
                 scale-project/, scale-rates/ sub-directories to activate this gate."
            );
            return;
        }
    };

    let scale_fixtures = [
        ("scale-county", "County-scale (CDB) inventory"),
        ("scale-project", "Project-scale (PDB) inventory"),
        ("scale-rates", "Rates-mode (County-scale CDB)"),
    ];

    println!(
        "\n[scale_fixtures_run_without_error] scale inputs root: {}",
        scale_root.display()
    );
    println!(
        "{:<42} {:>8} {:>8} {:>8}",
        "fixture", "planned", "executed", "unimpl"
    );
    println!("{}", "-".repeat(72));

    let mut failures: Vec<String> = Vec::new();

    for (fixture_name, label) in &scale_fixtures {
        let fixture_path = fixtures_dir().join(format!("{fixture_name}.xml"));
        if !fixture_path.is_file() {
            println!("{fixture_name:<42} SKIP (fixture XML not found)");
            continue;
        }

        let scale_input_dir = scale_root.join(fixture_name);
        if !scale_input_dir.is_dir() {
            println!(
                "{fixture_name:<42} SKIP (no scale-input dir: {})",
                scale_input_dir.display()
            );
            continue;
        }

        let out = tempdir().expect("tempdir");
        let result = run_simulation(&RunOptions {
            runspec: fixture_path.clone(),
            output: out.path().to_path_buf(),
            max_parallel_chunks: 1,
            calculator_dag: None,
            run_date_time: Some("2026-05-21T00:00:00".to_string()),
            snapshot: None,
            scale_input: Some(scale_input_dir),
        });

        match result {
            Err(e) => {
                failures.push(format!("{fixture_name}: {e}"));
                println!("{fixture_name:<42} ERROR");
            }
            Ok(outcome) => {
                if !outcome.run_record_path.is_file() {
                    failures.push(format!("{fixture_name}: MOVESRun.parquet missing"));
                }
                if outcome.modules_planned.is_empty() {
                    failures.push(format!("{fixture_name}: no modules planned"));
                }
                println!(
                    "{fixture_name:<42} {:>8} {:>8} {:>8}  ({label})",
                    outcome.modules_planned.len(),
                    outcome.modules_executed.len(),
                    outcome.modules_unimplemented.len(),
                );
            }
        }
    }

    println!("{}", "-".repeat(72));

    assert!(
        failures.is_empty(),
        "scale-fixture regression failures:\n  {}",
        failures.join("\n  ")
    );
}

/// Diff each scale fixture's port output against its canonical-MOVES snapshot.
///
/// **Doubly-dormant**: requires both [`SCALE_INPUTS_DIR_ENV`] (for the
/// CDB/PDB Parquet inputs) and [`SNAPSHOTS_DIR_ENV`] (for the reference
/// canonical-MOVES output).  When one or both are absent the test prints a
/// notice and passes without running any diff.
///
/// Note: at Task 144 author time, canonical MOVES was **not runnable** on the
/// implementation machine (SIF files were absent). The reference snapshots for
/// `scale-county`, `scale-project`, and `scale-rates` must be produced by a
/// separate run of `characterization/run-all-fixtures.sh --include scale-*`
/// on an Apptainer-capable HPC node.
#[test]
fn scale_canonical_snapshot_diff() {
    let scale_root = match scale_inputs_root() {
        Some(r) => r,
        None => {
            println!(
                "\n[scale_canonical_snapshot_diff] DORMANT\n\
                 Set {SCALE_INPUTS_DIR_ENV} to enable scale-fixture canonical diffs."
            );
            return;
        }
    };

    let snaps_root = snapshots_root();
    let scale_fixtures = ["scale-county", "scale-project", "scale-rates"];
    let covered: Vec<&str> = scale_fixtures
        .iter()
        .copied()
        .filter(|name| canonical_present(&snaps_root, name))
        .collect();

    if covered.is_empty() {
        println!(
            "\n[scale_canonical_snapshot_diff] DORMANT\n\
             No canonical scale snapshots under '{}'.\n\
             Generate them with: characterization/run-all-fixtures.sh \
             --include scale-county --include scale-project --include scale-rates\n\
             See docs/known-divergences.md for full instructions.",
            snaps_root.display()
        );
        return;
    }

    let opts = tolerance_opts();
    println!(
        "\n[scale_canonical_snapshot_diff] {} fixture(s) against {}",
        covered.len(),
        snaps_root.display()
    );

    let mut ok: Vec<&str> = Vec::new();
    let mut failures: Vec<String> = Vec::new();

    for fixture_name in &covered {
        let fixture_path = fixtures_dir().join(format!("{fixture_name}.xml"));
        if !fixture_path.is_file() {
            println!("{fixture_name}: SKIP — fixture XML not found");
            continue;
        }

        let scale_input_dir = scale_root.join(fixture_name);
        if !scale_input_dir.is_dir() {
            println!(
                "{fixture_name}: SKIP — scale-input dir {} not found",
                scale_input_dir.display()
            );
            continue;
        }

        let out = tempdir().expect("tempdir");
        let outcome = run_simulation(&RunOptions {
            runspec: fixture_path,
            output: out.path().to_path_buf(),
            max_parallel_chunks: 1,
            calculator_dag: None,
            run_date_time: Some("2026-05-21T00:00:00".to_string()),
            snapshot: None,
            scale_input: Some(scale_input_dir),
        })
        .unwrap_or_else(|e| panic!("{fixture_name}: run error — {e}"));

        let canonical = match Snapshot::load(&snaps_root.join(fixture_name)) {
            Ok(s) => s,
            Err(e) => {
                println!("{fixture_name}: SKIP — canonical load error: {e}");
                continue;
            }
        };

        let port = match Snapshot::load(outcome.output_root.as_path()) {
            Ok(s) => s,
            Err(e) => {
                println!("{fixture_name}: SKIP diff — port output not in snapshot format: {e}");
                continue;
            }
        };

        let diff = diff_snapshots(&canonical, &port, &opts);
        let s = diff.summary();

        if diff.is_empty() {
            ok.push(fixture_name);
        } else {
            failures.push(format!(
                "{fixture_name}: tables_added={} tables_removed={} tables_changed={} \
                 schema_diffs={} rows_added={} rows_removed={} cells_changed={}",
                s.tables_added,
                s.tables_removed,
                s.tables_changed,
                s.schema_diffs,
                s.rows_added,
                s.rows_removed,
                s.cells_changed,
            ));
        }
    }

    if !ok.is_empty() {
        println!("within tolerance ({}):", ok.len());
        for name in &ok {
            println!("  ok {name}");
        }
    }
    if !failures.is_empty() {
        println!("beyond tolerance ({}):", failures.len());
        for f in &failures {
            println!("  FAIL {f}");
        }
    }

    assert!(
        failures.is_empty(),
        "scale canonical-snapshot divergences beyond budget:\n  {}",
        failures.join("\n  ")
    );
}
