#!/bin/bash
# build-sif.sh — wrapper around `apptainer build` that pins versions,
# verifies prerequisites, and writes the resulting SIF SHA256 to
# characterization/canonical-image.lock.
#
# files/versions.env is the source of truth. To override values for a
# single build (without committing changes to versions.env), set the
# corresponding env vars before invoking this script — they get baked
# into a temp build context.
#
# Required (either in files/versions.env or as env vars):
#   MOVES_COMMIT       40-hex-char SHA of the EPA_MOVES_Model commit.
#   MOVESDB_SHA256     SHA256 of the movesdb20241112.zip used at build.
#
# Optional:
#   MOVESDB_LOCAL_PATH Host path to movesdb20241112 dir or zip.
#                      Directory  -> bind-mounted to /opt/seed/movesdb.
#                      .zip file  -> SHA-verified, unzipped to a temp
#                                    dir, then bind-mounted.
#   MOVESDB_URL        HTTPS URL used by %post when no local path is set.
#   GO_VERSION         Override the Go version pin.
#   OUTPUT             Output SIF path (default: ./canonical-moves.sif).
#   FAKEROOT           1 = use --fakeroot, 0 = use setuid mode (default
#                      auto-detected).

set -euo pipefail

HERE="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"
ROOT="$(cd "${HERE}/.." && pwd)"   # characterization/

OUTPUT="${OUTPUT:-${HERE}/canonical-moves.sif}"
LOCKFILE="${ROOT}/canonical-image.lock"

# Snapshot caller-provided env-var overrides BEFORE sourcing versions.env
# so they win over the file's defaults.
OV_MOVES_COMMIT="${MOVES_COMMIT:-}"
OV_MOVESDB_SHA256="${MOVESDB_SHA256:-}"
OV_MOVESDB_URL="${MOVESDB_URL:-}"
OV_GO_VERSION="${GO_VERSION:-}"

# shellcheck disable=SC1091
. "${HERE}/files/versions.env"

# Apply overrides on top of file defaults.
[ -n "${OV_MOVES_COMMIT}"   ] && MOVES_COMMIT="${OV_MOVES_COMMIT}"
[ -n "${OV_MOVESDB_SHA256}" ] && MOVESDB_SHA256="${OV_MOVESDB_SHA256}"
[ -n "${OV_MOVESDB_URL}"    ] && MOVESDB_URL="${OV_MOVESDB_URL}"
[ -n "${OV_GO_VERSION}"     ] && GO_VERSION="${OV_GO_VERSION}"

# Recompute Go-derived fields if GO_VERSION was overridden.
GO_TARBALL="go${GO_VERSION}.linux-amd64.tar.gz"
GO_DOWNLOAD_URL="https://go.dev/dl/${GO_TARBALL}"

# ----- Validate -----
if [ -z "${MOVES_COMMIT}" ] || [ "${MOVES_COMMIT}" = "REPLACE_WITH_PINNED_COMMIT_SHA" ]; then
    echo "FATAL: MOVES_COMMIT is not set." >&2
    echo "  Edit files/versions.env or pass it as an env var:" >&2
    echo "    MOVES_COMMIT=<40-hex-sha> $0" >&2
    exit 2
fi
if ! [[ "${MOVES_COMMIT}" =~ ^[0-9a-fA-F]{40}$ ]]; then
    echo "FATAL: MOVES_COMMIT must be a 40-hex-char SHA, got: ${MOVES_COMMIT}" >&2
    exit 2
fi
if [ -z "${MOVESDB_SHA256}" ] || [ "${MOVESDB_SHA256}" = "REPLACE_WITH_MOVESDB_SHA256" ]; then
    echo "FATAL: MOVESDB_SHA256 is not set in files/versions.env." >&2
    exit 2
fi

command -v apptainer >/dev/null 2>&1 || {
    echo "FATAL: apptainer not found in PATH." >&2
    exit 2
}

# ----- Detect fakeroot -----
if [ -z "${FAKEROOT:-}" ]; then
    if apptainer config global --get 'allow setuid' 2>/dev/null | grep -qi yes; then
        FAKEROOT=0
    else
        FAKEROOT=1
    fi
fi
FAKEROOT_FLAG=()
[ "${FAKEROOT}" = "1" ] && FAKEROOT_FLAG=( --fakeroot )

# ----- Build a temp context with the merged versions.env -----
CTX="$(mktemp -d)"
cleanup() { rm -rf "${CTX}"; }
trap cleanup EXIT

cp "${HERE}/canonical-moves.def" "${CTX}/canonical-moves.def"
mkdir -p "${CTX}/files"
cp "${HERE}/files/my.cnf" \
   "${HERE}/files/init-mariadb.sh" \
   "${HERE}/files/start-mariadb-bg.sh" \
   "${CTX}/files/"

# Write the merged versions.env into the temp context.
cat > "${CTX}/files/versions.env" <<EOF
# Generated by build-sif.sh — do not edit; edit the source at
# characterization/apptainer/files/versions.env instead.

MOVES_REPO_URL="${MOVES_REPO_URL}"
MOVES_COMMIT="${MOVES_COMMIT}"

MOVESDB_FILENAME="${MOVESDB_FILENAME}"
MOVESDB_SHA256="${MOVESDB_SHA256}"
MOVESDB_URL="${MOVESDB_URL}"

MARIADB_SERIES="${MARIADB_SERIES}"
JDK_PACKAGE="${JDK_PACKAGE}"

GO_VERSION="${GO_VERSION}"
GO_TARBALL="${GO_TARBALL}"
GO_DOWNLOAD_URL="${GO_DOWNLOAD_URL}"
GO_SHA256="${GO_SHA256}"
EOF

# ----- Stage local movesdb into the build context (if provided) -----
# Apptainer build doesn't support --bind mounts that need to create new
# destinations under --writable, so we ship the seed via %files instead.
# The def file's %post checks /opt/seed/movesdb first; if present, it
# wins over the in-repo zip.
SEED_STAGED=0
if [ -n "${MOVESDB_LOCAL_PATH:-}" ]; then
    SEED_DIR="${CTX}/files/seed"
    mkdir -p "${SEED_DIR}"
    if [ -d "${MOVESDB_LOCAL_PATH}" ]; then
        cp -a "${MOVESDB_LOCAL_PATH}/." "${SEED_DIR}/"
        SEED_STAGED=1
    elif [ -f "${MOVESDB_LOCAL_PATH}" ]; then
        # Verify SHA256 of the local zip against the pin (belt and suspenders;
        # the def file's %post re-verifies after copying in).
        echo "${MOVESDB_SHA256}  ${MOVESDB_LOCAL_PATH}" | sha256sum -c -
        cp "${MOVESDB_LOCAL_PATH}" "${SEED_DIR}/${MOVESDB_FILENAME}"
        SEED_STAGED=1
    else
        echo "FATAL: MOVESDB_LOCAL_PATH=${MOVESDB_LOCAL_PATH} does not exist." >&2
        exit 2
    fi
fi

# Splice an extra %files entry into the def for the seed dir if staged.
# Insertion happens after the existing %files header so the static
# entries are unchanged. The path is relative to the build context, so
# "files/seed" matches the directory we just created.
if [ "${SEED_STAGED}" = "1" ]; then
    awk '
        /^%files/ && !done {
            print
            print "    files/seed                /opt/seed/movesdb"
            done = 1
            next
        }
        { print }
    ' "${CTX}/canonical-moves.def" > "${CTX}/canonical-moves.def.staged"
    mv "${CTX}/canonical-moves.def.staged" "${CTX}/canonical-moves.def"
fi

echo "[build-sif] Building ${OUTPUT}"
echo "[build-sif]   MOVES_COMMIT  = ${MOVES_COMMIT}"
echo "[build-sif]   GO_VERSION    = ${GO_VERSION}"
echo "[build-sif]   FAKEROOT      = ${FAKEROOT}"
echo "[build-sif]   MOVESDB src   = ${MOVESDB_LOCAL_PATH:-${MOVESDB_URL:-(in MOVES tree)}}"

# %files relative paths in the def are resolved against apptainer's
# working directory, so cd to the build context before invoking.
( cd "${CTX}" && apptainer build \
    "${FAKEROOT_FLAG[@]}" \
    --force \
    "${OUTPUT}" \
    "${CTX}/canonical-moves.def" )

# ----- Compute and record the hash -----
SIF_SHA256="$(sha256sum "${OUTPUT}" | awk '{print $1}')"
SIF_BYTES="$(stat -c '%s' "${OUTPUT}")"
BUILD_DATE="$(date -u +%Y-%m-%dT%H:%M:%SZ)"
BUILD_HOST="$(hostname)"
APPTAINER_VERSION="$(apptainer --version | awk '{print $NF}')"

cat > "${LOCKFILE}" <<EOF
# canonical-image.lock — pinned identity of the canonical-moves SIF.
#
# Downstream beads (mo-1s9o, mo-abxb, mo-zik2, …) MUST reference the SIF
# by this hash. Any rebuild that produces a different hash invalidates
# downstream characterization snapshots and is a deliberate cutover.
#
# Regenerate by running characterization/apptainer/build-sif.sh.

sif_path           = "characterization/apptainer/canonical-moves.sif"
sif_sha256         = "${SIF_SHA256}"
sif_bytes          = ${SIF_BYTES}

# Source pins
moves_repo_url     = "${MOVES_REPO_URL}"
moves_commit       = "${MOVES_COMMIT}"

# Default DB
movesdb_filename   = "${MOVESDB_FILENAME}"
movesdb_sha256     = "${MOVESDB_SHA256}"

# Toolchain pins
mariadb_series     = "${MARIADB_SERIES}"
jdk_package        = "${JDK_PACKAGE}"
go_version         = "${GO_VERSION}"

# Build provenance
built_at_utc       = "${BUILD_DATE}"
built_on_host      = "${BUILD_HOST}"
apptainer_version  = "${APPTAINER_VERSION}"
EOF

echo
echo "[build-sif] Wrote ${LOCKFILE}"
echo "[build-sif] SHA256: ${SIF_SHA256}"
echo "[build-sif] Bytes:  ${SIF_BYTES}"
